/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apex.view;

import apex.DAO.ClientesDAO;
import apex.DAO.ConexaoDAO;
import apex.DTO.ClientesDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mnPrincipal = new javax.swing.JMenuBar();
        mnVendas = new javax.swing.JMenu();
        mnRealizarVenda = new javax.swing.JMenuItem();
        mnConsultaVenda = new javax.swing.JMenuItem();
        mnClientes = new javax.swing.JMenu();
        mnCadastrarCliente = new javax.swing.JMenuItem();
        mnProdutos = new javax.swing.JMenu();
        mnCadastrarProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\apex\\ApexTurma3\\Apex - Java Fundamentos\\PojetoMercado\\carrinho.png")); // NOI18N

        mnVendas.setText("Vendas");

        mnRealizarVenda.setText("Realizar venda");
        mnRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRealizarVendaActionPerformed(evt);
            }
        });
        mnVendas.add(mnRealizarVenda);

        mnConsultaVenda.setText("Consultar venda");
        mnVendas.add(mnConsultaVenda);

        mnPrincipal.add(mnVendas);

        mnClientes.setText("Clientes");

        mnCadastrarCliente.setText("Cadastrar");
        mnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarClienteActionPerformed(evt);
            }
        });
        mnClientes.add(mnCadastrarCliente);

        mnPrincipal.add(mnClientes);

        mnProdutos.setText("Produtos");

        mnCadastrarProduto.setText("Cadastar");
        mnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarProdutoActionPerformed(evt);
            }
        });
        mnProdutos.add(mnCadastrarProduto);

        mnPrincipal.add(mnProdutos);

        setJMenuBar(mnPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarClienteActionPerformed
         ClientesView tela = new ClientesView();
         tela.setVisible(true);
      
    }//GEN-LAST:event_mnCadastrarClienteActionPerformed

    private void mnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarProdutoActionPerformed
       ProdutosView tela = new ProdutosView();
       tela.setVisible(true);
    }//GEN-LAST:event_mnCadastrarProdutoActionPerformed

    private void mnRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRealizarVendaActionPerformed
        VendasView tela = new VendasView();
        tela.setVisible(true);
    }//GEN-LAST:event_mnRealizarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem mnCadastrarCliente;
    private javax.swing.JMenuItem mnCadastrarProduto;
    private javax.swing.JMenu mnClientes;
    private javax.swing.JMenuItem mnConsultaVenda;
    private javax.swing.JMenuBar mnPrincipal;
    private javax.swing.JMenu mnProdutos;
    private javax.swing.JMenuItem mnRealizarVenda;
    private javax.swing.JMenu mnVendas;
    // End of variables declaration//GEN-END:variables
}
